version: "3.7"

services:
  app:
    working_dir: /app
    container_name: go
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: .
        target: /app
    ports:
      - 8080:8080
      - 2345:2345
    depends_on:
      - db
    tty: true

  db:
    image: postgres:15.3-bullseye
    ports:
      - "5435:5432"
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=db
    volumes:
      - psql-data:/var/lib/postgresql/data

volumes:
  psql-data:
